# Generated by Django 4.1.7 on 2023-10-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Syatem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
